Repository BaraniVA/Habitheat, pull requests merged in 2025-07, with the labels that each got.

#8 Navbar responsiveness issue fixed
  project/src/components/Header.tsx
Labels: Level 2, gssoc25

#49 UI Enhancement: Show selected mood label & dynamic stress/energy bar colors
  project/src/components/MoodTracker.tsx
Labels: Level 1, gssoc25

#51 Add animation
  project/package-lock.json
  project/package.json
  project/src/components/Header.tsx
Labels: Level 1, gssoc25

#80 Save Template and share option
  project/src/App.tsx
  project/src/components/HabitCard.tsx
  project/src/components/HabitDetail.tsx
  project/src/components/SaveAsTemplateModal.tsx
  project/src/hooks/useHabits.ts
  project/src/pages/Dashboard.tsx
  project/src/pages/HabitTemplatesView.tsx
  project/src/types/index.ts
  project/src/utils/habitTemplates.ts
  project/src/utils/storage.ts
Labels: Level 3, gssoc25

#93 Add Edit Habit functionality
  frontend/src/App.tsx
  frontend/src/components/HabitCard.tsx
  frontend/src/components/UpdateHabitModal.tsx
  frontend/src/hooks/useHabits.ts
  frontend/src/pages/Dashboard.tsx
Labels: Level 2, gssoc25

#97 resolved the conflits done adding animations
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/AchievementsView.tsx
  frontend/src/pages/ChallengesView.tsx
  frontend/src/pages/Dashboard.tsx
  frontend/src/pages/HabitTemplatesView.tsx
  frontend/src/pages/InsightsView.tsx
  frontend/src/pages/MoodTracker.tsx
  frontend/src/pages/ProfilePage.tsx
Labels: Level 3, gssoc25

#107 habits_api: added
  backend/.env.example
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/bulkController.js
  backend/src/controllers/habitController.js
  backend/src/db/connect.js
  backend/src/middleware/errorHandler.js
  backend/src/middleware/ratelimiting.js
  backend/src/middleware/validation.js
  backend/src/models/habitModel.js
  backend/src/routes/bulkRoutes.js
  backend/src/routes/habitRoutes.js
  backend/src/utils/fileHandler.js
  backend/src/utils/sanitizer.js
Labels: Level 3, gssoc25
